jc_platform_home:
  path: /{page}
  defaults: {_controller: JCPlatformBundle:Advert:index, page: 1}
  requirements:
      page: \d*

jc_platform_view:
  path: /advert/{id}
  defaults: {_controller: JCPlatformBundle:Advert:view}
  requirements: 
      id: \d+

jc_platform_add:
  path: /add
  defaults: {_controller: JCPlatformBundle:Advert:add}

jc_platform_edit:
  path: /edit/{id} 
  defaults: {_controller: JCPlatformBundle:Advert:edit}
  requirements:
      id: \d+

jc_platform_delete:
  path: /delete/{id}
  defaults: {_controller: JCPlatformBundle:Advert:delete}
  requirements:
      id: \d+