services:

  jc_platform.antispam:
    class: JC\PlatformBundle\AntiSpam\JCAntiSpam
    arguments:
      - "@mailer"
      - %locale%
      - 50
#    jc_platform.example:
#        class: JC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
